### ISSUE TITLE
/etc/skel files in /root should be copied by tmpfiles

### ISSUE THREAD

**Issue by ajeddeloh** [coreos/fedora-coreos-config#136]
Having a systemd service to copy a file on first boot seems hacky. We ought to convert it to a tmpfiles rule and let tmpfiles handle it.

We could even just use symlinks since we're not modifying the files.

**Comment by jlebon** [comment]
Oh neat, just saw the `C` entry type. Hadn't realized systemd-tmpfiles could do this. Yeah, I think we can and should do this.

**Comment by jlebon** [comment]
> We could even just use symlinks since we're not modifying the files.

I don't think we want to do this though. First, it'd mean that all other user's homes are different from `/root` in that respect, but also a naive `vi /root/.bashrc` will actually end up modifying the template instead of just for the root user.

**Comment by jlebon** [comment]
OK, now I see this is addressed in: https://github.com/coreos/fedora-coreos-config/pull/137.

**Comment by jlebon** [comment]
Ahh OK, the symlinks as proposed in #137 are actually to `/usr/etc`, which makes this better. Though the UX of having to unlink and copy in order to edit one of those files is a bit odd. Having to hardcode the list of skeleton files is also unfortunate.

Hmm, actually another UX issue too is that one can't easily just append to the default config anymore. (See the commit message in https://github.com/coreos/fedora-coreos-config/pull/83#issue-272861713).
