### ISSUE TITLE
tests: covert tests/manual/ to auto

### ISSUE THREAD

**Issue by HuijingHei** [coreos/fedora-coreos-config#1410]
tests/manual/coreos-docs-net-testing.sh and tests/manual/coreos-network-testing.sh are networking test scripts that not included in CI, we can covert them to auto under kola. @dustymabe do you have any suggestions about this?

**Comment by HuijingHei** [comment]
[coreos-docs-net-testing.sh](https://github.com/coreos/fedora-coreos-config/blob/629fe2190c11092a595c78826910085b2d8c4be6/tests/manual/coreos-docs-net-testing.sh) includes 6 test scenarios in two ways:
- via the dracut kernel networking arguments
- via the NM keyfiles provided by Ignition ( using `$ /usr/libexec/nm-initrd-generator -s -- $kargs` )

1. static ip for nic
> - ip=10.10.10.10::10.10.10.1:255.255.255.0:staticip:eth1:none:8.8.8.8

2. static ip for bond
> - ip=10.10.10.10::10.10.10.1:255.255.255.0:staticbond:bond0:none:8.8.8.8
> - bond=bond0:eth1,eth2:mode=active-backup,miimon=100

3. static ip for vlan
> - ip=10.10.10.10::10.10.10.1:255.255.255.0:staticvlan:eth1.100:none:8.8.8.8
> - vlan=eth1.100:eth1

4. dhcp for bridge
> - ip=br0:dhcp
> - bridge=br0:eth1,eth2

5. dhcp for team
> - ip=team0:dhcp
> - team=team0:eth1,eth2

6. dhcp for vlan on bond
> - ip=bond0.100:dhcp
> - bond=bond0:eth1,eth2:mode=active-backup,miimon=100
> - vlan=bond0.100:bond0

**Comment by HuijingHei** [comment]
[coreos-network-testing.sh](https://github.com/coreos/fedora-coreos-config/blob/629fe2190c11092a595c78826910085b2d8c4be6/tests/manual/coreos-network-testing.sh) includes the following scenarios:
- Testing ifcfg file via Ignition disables initramfs propagation

- Testing coreos.no_persist_ip disables initramfs propagation

- Testing coreos.force_persist_ip forces initramfs propagation

- Testing initramfs nameserver= option

- Testing net.ifnames=0 gives us legacy NIC naming

- loop (need to do more investigation)

**Comment by dustymabe** [comment]
The `coreos-docs-net-testing.sh` just tries to test [our documentation](https://docs.fedoraproject.org/en-US/fedora-coreos/sysconfig-network-configuration/) to make sure it all works. So that's where those test cases come from.

`coreos-network-testing.sh` tries to be more exhaustive. The loop basically tries to test every combination of NIC type (i.e. bond, vlan, bridge, etc) with each combination of passed in networking config (kargs or Ignition config). If we want to test every combination (not saying we have to) would probably be best if we generated the tests from a script periodically and then committed that to git.

**Comment by HuijingHei** [comment]
Thanks @dustymabe for your info, maybe I shall start this in the next sprint. I will contact to you if there are something that need your help

**Comment by HuijingHei** [comment]
Close this as this is done.
