### ISSUE TITLE
Switch OVA to use EFI by default

### ISSUE THREAD

**Issue by cgwalters** [coreos/fedora-coreos-config#1494]
We're getting some requests downstream to flip to EFI by default (maybe to make it easier to use secure boot?), word on the street is all that is required is:

`<vmw:Config ovf:required="false" vmw:key="firmware" vmw:value="efi"/>`

Relevant code is around https://github.com/coreos/coreos-assembler/blob/ed753cb08232a107c7eebda495428630b24cf1da/src/cosalib/ova.py#L81

One concern I have here is around supporting older vSphere instances.  IIRC we tried to bump something in the past around the base hardware spec and hit that.

**Comment by miabbott** [comment]
> One concern I have here is around supporting older vSphere instances. IIRC we tried to bump something in the past around the base hardware spec and hit that.

Related to this discussion https://bugzilla.redhat.com/show_bug.cgi?id=2050452

We may be able to make these changes as part of the OCP/RHCOS 4.11 release, but we should be really be certain that we can drop support for older vSphere versions (i.e. below 6.5u3) before we make any changes to the OVF metadata.  Just so we don't end up in a position of having to support two versions of the OVF: one for FCOS + one for RHCOS.

Tagging @jcpowermac because he was involved in the downstream discussions
