### ISSUE TITLE
Sharing information between FCOS and SCOS/RHCOS9

### ISSUE THREAD

**Issue by marmijo** [coreos/fedora-coreos-config#1878]
Configuration information from manifests, overlays, and kola tests can be shared between FCOS and RHCOS. However, there is no way to share this information between FCOS and SCOS/RHCOS9 without RHCOS8 also inheriting it. We should choose a way to share this information between FCOS and SCOS/RHCOS9 separately so that it's not also inherited by RHCOS8.

Some example use cases are [coreos/fedora-coreos-config#1844](https://github.com/coreos/fedora-coreos-config/pull/1844) and [COS-1591](https://issues.redhat.com/browse/COS-1591).

Some initial discussion in [coreos/fedora-coreos-config#1844](https://github.com/coreos/fedora-coreos-config/pull/1844).

**Comment by cgwalters** [comment]
What I hope is that soon, RHCOS8 goes into maintenance mode effectively, and we turn our focus to RHCOS9.  When that happens, I think what makes the most sense is to have it only live on a separate git branch.  And then, changes to this repository (fedora-coreos-config) then are only shared by default with RHCOS9 - fixing the problem here.

IOW, while this is a real problem today, let's also not overly complicate/optimize things for what I think will be a (relatively) transient state.

It is a bit tempting actually to try to make that split happen right now - the cost though will be we'll need to do e.g. `/cherrypick release-4.12-rhcos8` or so for PRs that do need to apply there.

OTOH, a git branch somewhat obviates all the work to have one git branch share configs.

**Comment by travier** [comment]
I don't think we should branch 4.12 early as it will only make us do more work. I think we already have the means to partially share overlays, manifests and tests and we should use that:
- overlays: Add a `06el9` or `06el9plus` overlay for configs that is FCOS + SCOS/RHEL9 only. We will merge it into FCOS later once we drop RHEL 8 support. We may also need a c9s specific overlay for changes that are available in SCOS but not RHCOS 9 yet but we can do that later.
- manifests: We have the split between FCOS, SCOS & RHCOS (each versions) already established.
- tests: we can re-use the `ID` checks from `/etc/os-release` but it's generally better to directly check for the feature or functionality being available than to check for a given version.

**Comment by bgilbert** [comment]
For manifests, should we add a manifest fragment that's included by both the FCOS and the SCOS/RHEL9 manifests?  We have at least one package (ssh-key-dir) that fits into that category, though of course we could just list it in both top-level manifests.

**Comment by travier** [comment]
Added [openshift/os@`0188112` (#905)](https://github.com/openshift/os/pull/905/commits/018811264851047b9603d2ec3034c33d81ad1a6f) in https://github.com/openshift/os/pull/905 to test that.

**Comment by cgwalters** [comment]
Yeah, I'm fine with a `06el9` overlay.

**Comment by travier** [comment]
I'll close this one as I don't think there more to do here. The changes I mentioned above are in https://github.com/openshift/os/commit/85fd274d4a70e09338585e5c2f1406083f44afa4.

When the need comes, you can add a `06el9` overlay in `fedora-coreos-config` and add a symlink in a submodule bump in `openshift/os`.
