### ISSUE TITLE
Consider moving CI to jenkins-fedora-coreos

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-config#199]
PR CI runs in jenkins-projectatomic-ci.apps.ci.centos.org, which is an additional namespace developers need access to in order to be able to e.g. rerun jobs.  Consider moving to jenkins-fedora-coreos.apps.ci.centos.org.

**Comment by dustymabe** [comment]
I agree that we should move it to a different namespace than projectatomic-ci but i'm not sure about moving it to our prod pipeline namespace (seems cleaner to keep it separate?). Are there any risks that we can identify with re-using the namespace?

**Comment by jlebon** [comment]
Right, the `projectatomic-ci` one was just to get us bootstrapped quickly since it already existed. We have a request out to create a new `coreos-ci` project to replace it: https://bugs.centos.org/view.php?id=16519.

> which is an additional namespace developers need access to in order to be able to e.g. rerun jobs

One ugly hack for this is to just [`git restamp`](https://github.com/jlebon/files/blob/7498ece4e273ccf34b8de29c9769849724ff8435/dotfiles/.gitconfig#L50) and push it out again.

> Are there any risks that we can identify with re-using the namespace?

Yeah, I'd also be wary of re-using the production project for this. Mostly because having them separate clearly makes accidental/malicious credential leaks much less likely. Also note the prod Jenkins is currently hidden for anonymous users.

(Not to say we shouldn't share more code between the two, we definitely could and should!)

**Comment by cgwalters** [comment]
This was fixed.
