### ISSUE TITLE
Detect package downgrades in CI

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-config#841]
To avoid events like https://github.com/coreos/fedora-coreos-config/pull/834, we should have an overridable CI check that notices package downgrades in override PRs.

**Comment by cgwalters** [comment]
Yes.  But: the current behavior of rpm-ostree is very intentional because in software we so often break things in new versions.  And downgrading/reverting should be *easy* and obvious.  Particularly for e.g. the Linux kernel.

Today in traditional Fedora (yum) and Debian w/apt, the package managers are obsessed with version numbers going up, which means every time there's a kernel regression the reaction is "file a bug and leave it broken" because there isn't a sane way to revert.  But in many cases, reverting is the right thing.

Anyways yes, probably rpm-ostree should gain a `--disallow-downgrades` flag or perhaps a `--allow-downgrade kernel` whitelist or so.  Maybe we can have this be part of the lockfiles.

**Comment by bgilbert** [comment]
Right, I think rpm-ostree allowing downgrades is fine and useful; I don't actually think we need any changes there.  But in the FCOS release tooling, I think it makes sense to take advantage of the fact that version numbers usually go up, and require an explicit statement that a downgrade is intentional.

**Comment by jlebon** [comment]
There's room for improvement, but this was done in https://github.com/coreos/fedora-coreos-config/pull/892.
